Blog/urls.py
from django.urls import path

from . import views

app_name = "Blog"
urlpatterns = [
    path("", views.blog_list, name="blog"),
    path("blog/<int:blog_id>", views.blog_detail, name="blog_detail"),
    path("blog/<int:blog_id>/<int:comment_id>", views.blog_reply, name="blog_reply"),
    path("blog/a_propos", views.blog_a_propos, name="a_propos"),
]

handler400 = 'Blog.views.bad_request'
handler403 = 'Blog.views.permission_denied'
handler404 = 'Blog.views.page_not_found'
handler500 = 'Blog.views.server_error'

BlogLabInfo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Blog/models.py
from ckeditor.fields import RichTextField
from django.core.exceptions import ValidationError
from django.db import models
import django.utils.timezone
import datetime

from django.db.models import SET_NULL


class Theme(models.Model):
    theme_name = models.CharField(max_length=100)
    theme_icon = models.CharField(max_length=100)

    def __str__(self):
        return self.theme_name

    def print_icon(self):
        return f"<i class='text-4xl {self.theme_icon}'></i>"


class Blog(models.Model):
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=400, null=True, blank=True)
    date = models.DateField(default=django.utils.timezone.now)
    content = RichTextField(null=True, blank=True)
    author = models.CharField(max_length=200, null=True, blank=True)
    theme = models.ForeignKey('Theme', on_delete=SET_NULL, null=True, blank=True
                              , related_name='Blogs')
    visible = models.BooleanField(default=True, null=True, blank=True)

    def __str__(self):
        return self.title

    def get_content(self):
        return self.content.order_by('position').all()


class Comment(models.Model):
    blog = models.ForeignKey('Blog', on_delete=models.CASCADE,
                             related_name='comments', null=True, blank=True)
    parent = models.ForeignKey('self', on_delete=models.CASCADE,
                               related_name='replies', null=True, blank=True)
    name = models.CharField(max_length=200)
    comment = models.TextField()
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.comment

Blog/forms.py
from django import forms
from .models import Blog, Comment
import datetime


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'description', 'author', 'theme', 'content',
                  'visible']
        exclude = ['date']

    def clean(self):
        cleaned_data = super().clean()
        title = cleaned_data.get('title')
        description = cleaned_data.get('description')
        date = datetime.date.today()
        if not title and not description and not date:
            raise forms.ValidationError('You have to write something!')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'comment']
        labels = {
            'name': '',
            'comment': ''
        }
        widgets = {
            'comment': forms.Textarea(attrs={'rows': 3,
                                             'placeholder': 'Votre commentaire'}),
            'name': forms.TextInput(attrs={'placeholder': 'Votre pseudonyme'})
        }

    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get('name')
        comment = cleaned_data.get('comment')
        if not name and not comment:
            raise forms.ValidationError('You have to write something!')

Blog/views.py
from django.shortcuts import render, redirect
from .models import Blog, Comment
from .forms import CommentForm


def blog_list(request):
    return render(request, 'Blog/index.html', {
        "blogs": Blog.objects.filter(visible=True).order_by("-date"),
        "unpublished_blogs": Blog.objects.filter(visible=False).order_by("-date"),
        "user": request.user,
        "title": "Lab'info"
    })


def blog_detail(request, blog_id):
    blog_choosed = Blog.objects.get(id=blog_id)
    comments = blog_choosed.comments.filter(parent=None).order_by("-date")
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.parent = None
            comment.blog = blog_choosed
            comment.save()
            return redirect('Blog:blog_detail', blog_id=blog_id)
    else:
        form = CommentForm()
    return render(request, 'Blog/blog.html', {
        "blog": blog_choosed,
        "comments": comments,
        "form": form,
        "title": blog_choosed.title
    })


def blog_reply(request, blog_id, comment_id):
    blog_choosed = Blog.objects.get(id=blog_id)
    comments = blog_choosed.comments.all().order_by("-date")
    comment_choosed = comments.get(id=comment_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.parent = comment_choosed
            comment.blog = blog_choosed
            comment.save()
            return redirect('Blog:blog_detail', blog_id=blog_id)
    else:
        form = CommentForm()
    return render(request, 'Blog/blog.html', {
        "blog": blog_choosed,
        "comments": comments,
        "form": form,
        "title": blog_choosed.title
    })


def blog_a_propos(request):
    return render(request, 'Blog/a_propos.html', {
        "blogs": Blog.objects.all(),
        "comments": Comment.objects.all(),
        "title": "A propos"
    })


def bad_request(request, exception):
    return render(request, 'Blog/error.html', {
        "error": "400 Bad Request",
        "message": "Your browser sent a request that this server could not "
                   "understand."
    })


def permission_denied(request, exception):
    return render(request, 'Blog/error.html', {
        "error": "403 Forbidden",
        "message": "You don't have permission to access the requested resource."
    })


def page_not_found(request, exception):
    return render(request, 'Blog/error.html', {
        "error": "404 Not Found",
        "message": "The requested resource was not found on this server."
    })


def server_error(request):
    return render(request, 'Blog/error.html', {
        "error": "500 Internal Server Error",
        "message": "The server encountered an internal error and was unable "
                   "to complete your request."
    })

Blog/templates/Blog/a_propos.html
{% include 'Blog/utils/css.html' %}
{% include 'Blog/utils/header.html' %}

<div class="flex flex-row justify-center">

    <div class="w-full lg:p-4 lg:w-1/3">
        <div class="container text-left">
            <h1 class="text-3xl font-semibold">A propos</h1>
            <p class="mt-4 text-lg">
                Ce site web a été réalisé pour le Lab'info de Polytech Tours. Il a
                pour but de regrouper des informations plus ou moins simples sur
                l'informatique, hardware ou software. Les différents blogs ont pour
                but d'être facilement compréhensible et suffisamment complet.
            </p>
            <p class="mt-4 text-lg">
                Le site contient <span class="font-semibold">{{ blogs.all.count }}</span> blogs et
                <span class="font-semibold">{{ comments.all.count }}</span> commentaires.
            </p>
            <p class="mt-4 text-lg">
                Ce site web a été réalisé par Mattéo Langlois avec le framework
                python Django et le Framework JavaScript Tailwind pour le
                front-end. Les icônes viennent de Fontawesome.
            </p>

        </div>
    </div>
</div>

Blog/templates/Blog/blog.html
{% extends "Blog/utils/header.html" %}
{% block content %}

<script>
    function openModal(idForm, idBtn) {
        document.getElementById(idForm).classList.remove('hidden');
        document.getElementById(idBtn).classList.add('hidden');
    }

    function closeModal(idForm, idBtn) {
        document.getElementById(idForm).classList.add('hidden');
        document.getElementById(idBtn).classList.remove('hidden');
    }
</script>
<div class="flex flex-row justify-center">
    <div class="w-full lg:p-4 lg:w-1/2">
        <div class="container">
            <h3 class="text-3xl font-bold text-center">{{ blog }}</h3>
            <div class="text-lg text-center text-gray-500">
                {{ blog.date }} - {{ blog.author }}
            </div>
            <div class="mt-4 text-black text-2xl text-left">
                {{ blog.content | safe }}
            </div>
        </div>

        <div class="title-container">
            <h3 class="container title lg:w-2/3">Commentaires</h3>
        </div>


        <div class="mt-4 flex flex-row justify-center">
            {% include 'Blog/forms/commentForm.html' %}
        </div>

        {% if comments %}
            <div class="container">
            {% for comment in comments %}
                <div class="flex flex-row justify-between w-full">
                    <div>
                        <div class="text-3xl">
                            {{ comment.name }} - <span class="font-light">{{ comment.date }}</span>
                        </div>
                        <div class="mt-2 text-2xl">
                            {{ comment.comment}}
                        </div>
                    </div>
                    <button id="btn-{{ comment.id }}" class="text-4xl send-button"
                            onclick="openModal('modalReply-{{ comment.id }}', 'btn-{{ comment.id }}')">
                        <i class="fa-solid fa-reply"></i>
                    </button>
                    {% include 'Blog/forms/replyForm.html' with id=comment.id %}
                </div>
                {% for reply in comment.replies.all|dictsort:"date" %}
                        <div class="flex flex-row justify-between lg:w-4/5 mt-10">
                            <div class="ml-10">
                                <div class="text-lg">
                                    {{ reply.name }} - <span class="font-light">{{ reply.date }}</span>
                                </div>
                                <div class="mt-2">
                                    {{ reply.comment }}
                                </div>
                            </div>
                            <button id="btnBis-{{ reply.id }}"  class="text-2xl send-button"
                                    onclick="openModal('modalReply-{{ reply.id }}', 'btn-{{ reply.id }}')">
                                <i class="fa-solid fa-reply"></i>
                            </button>
                            {% include 'Blog/forms/replyForm.html' with id=reply.id %}
                        </div>
                {% endfor %}
                <hr>
            {% endfor %}
            </div>
        {% endif %}
    </div>
</div>
{% endblock %}

Blog/templates/Blog/blog_card.html
<a class="transition-card container w-full mt-1 mb-1 lg:mt-3 lg:m-1" href="{% url 'Blog:blog_detail' blog.id %}">
    <div class="p-4 flex row-auto">
        {{ blog.theme.print_icon | safe }}
        <p class="text-lg font-semibold ml-4">{{ blog }}</p>
    </div>
    <div class="flex flex-row justify-between">
        <div class="p-4 border-t border-gray-200">
            <p class="text-sm">{{ blog.description }}</p>
            <p class="text-sm text-gray-500">{{ blog.date }} | {{ blog.author }}</p>
        </div>
        <button class="text-4xl mr-5 hover:text-gray-300 ease-in-out duration-150"><i class="fa-solid fa-arrow-right"></i></button>
    </div>
</a>

Blog/templates/Blog/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

Blog/templates/Blog/forms/commentForm.html
<form action="{% url 'Blog:blog_detail' blog.id %}" method="post" class="container w-full lg:w-1/2">
    <div class="flex flex-row justify-end w-full pr-5">
        <div class="flex flex-col justify-evenly ">
            <h3 class="text-3xl mb-3">Ajouter un commentaire</h3>
            {% csrf_token %}
            {{ form.as_div }}
        </div>
    </div>
        <button class="bg-contrast text-white p-2 rounded float-right text-3xl" type="submit">
            <i class="fa-solid fa-plus"></i>
        </button>
</form>

Blog/templates/Blog/forms/replyForm.html
<form action="{% url 'Blog:blog_reply' blog.id id %}" method="post"
      class="hidden" id="modalReply-{{ id }}">
    <div class="flex flex-row justify-end w-full">
        <button class="send-button text-4xl"
                onclick="closeModal('modalReply-{{ id }}', 'btn-{{ id }}')">
            <i class="fa-solid fa-close"></i>
        </button>
    </div>

    <div class="flex flex-col justify-evenly ">
        <h3 class="text-3xl mb-3">Ajouter un commentaire</h3>
        {% csrf_token %}
        {{ form.as_div }}
    </div>
    <button class="bg-contrast text-white p-2 rounded float-right text-3xl" type="submit">
        <i class="fa-solid fa-plus"></i>
    </button>
</form>

Blog/templates/Blog/index.html
{% extends "Blog/utils/header.html" %}
{% block content %}

    <div class="flex flex-row justify-center">
        <div class="w-full lg:p-4 lg:w-2/3">
            <div class="title-container">
                <h1 class="container title lg:w-2/3">Listes des blogs : </h1>
            </div>

            <section class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                {% for blog in blogs %}
                    {% include 'Blog/blog_card.html' %}
                {% endfor %}
                {% if user.is_authenticated %}

            </section>
            <div class="title-container">
                <h1 class="container title lg:w-2/3">Blogs non publiés : </h1>
            </div>
            <section class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                    {% for blog in unpublished_blogs %}
                        {% include 'Blog/blog_card.html' %}
                    {% endfor %}
                {% endif %}
            </section>
        </div>
    </div>
{% endblock %}

Blog/templates/Blog/utils/css.html
{% load static tailwind_tags %}

<head>
    <script src="https://kit.fontawesome.com/f0c5800638.js" crossorigin="anonymous"></script>
    <title>{{ title }}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/dist/styles.css' %}">
    {% tailwind_css %}
</head>

Blog/templates/Blog/utils/header.html
{% load static tailwind_tags %}
{% load static %}
{% include "Blog/utils/css.html" %}

<!DOCTYPE html>
<header class="bg-contrast text-white p-4">
    <h1 class="text-5xl font-bold text-white">
        <a href="{% url 'Blog:blog' %}" class=" text-white hover:text-gray-200">Lab'info</a>
    </h1>
    <nav class="mt-4 flex flex-col lg:flex-row">
        <a class="text-3xl mr-4 hov-txt mb-4" href="{% url 'Blog:blog' %}">Listes des blogs</a>
        <a class="lg:ml-4 text-3xl hov-txt mb-4" href="{% url 'Blog:a_propos' %}">A propos</a>
    </nav>
</header>
<body class="bg-primary font-sans-serif leading-normal tracking-normal">

{% block content %}

{% endblock %}

</body>